### ISSUE TITLE
New Intel error on jlse

### ISSUE THREAD

**Issue by mrnorman** [mrnorman/YAKL#102]
Using current main, hash: d706e2f44fb8f5651cb2f6f3748e6fd3261a70ae

```bash
qsub -I -t 120 -n 1 -q arcticus
```

```bash
source source jlse_gpu_O3.sh
make -j
make test
```

```bash
[ac.normanmr@arcticus09:~/YAKL/unit/build/machines/jlse] >:O ./CArray/CArray 
terminate called after throwing an instance of 'sycl::_V1::runtime_error'
  what():  No device of requested type 'info::device_type::gpu' available. Please check https://software.intel.com/content/www/us/en/develop/articles/intel-oneapi-dpcpp-system-requirements.html -1 (PI_ERROR_DEVICE_NOT_FOUND)
Aborted
```

**Comment by mrnorman** [comment]
@abagusetty, @omarkahmed, any ideas what might cause this?

**Comment by abagusetty** [comment]
that is new one, will take a look. `arcticus` is deprecated hardware to be replaced with `florentia` (aka PVC). Looks like a new environment variable to be updated in the script.

**Comment by omarkahmed** [comment]
@mrnorman , this looks like an issue where the newer user mode driver (UMD) breaks on this deprecated GPU (ATS).  Try executing the following after loading your modules:
module switch -f intel_compute_runtime/release/agama-devel-551 intel_compute_runtime/release/agama-prerelease-475

**Comment by abagusetty** [comment]
Great, any ATS are just deprecated and no software support. Do you think we should drop the ATS files and move to florentia instead as that is more relevant ?

**Comment by mrnorman** [comment]
I'm fine with that. We do seem to have a problem with the streams unit test on florentia still: https://github.com/mrnorman/YAKL/issues/103

**Comment by mrnorman** [comment]
Moved to Kokkos or omitted by streams removal.
