### ISSUE TITLE
YAKL reduction APIs

### ISSUE THREAD

**Issue by abagusetty** [mrnorman/YAKL#110]
@mrnorman  Question regarding the APIs for reductions and wanted to check before putting a PR. The idea is to prevent (a) the user specify the size (b) use the raw pointer to get the reduction done.

Currently the way the reductions are implemented as follows:
```c++
    yakl::ParallelSum<real,memDevice> psum(data.totElems());
    real sum = psum( data.data() );

    yakl::ParallelMin<real,memDevice> pmin(data.totElems());
    real min = pmin( data.data() );

    yakl::ParallelMax<real,memDevice> pmax(data.totElems());
    real max = pmax( data.data() );
```
to
```c++
    sum = yakl::ParallelSum<real,memDevice>(data);
    min = yakl::ParallelMin<real,memDevice>(data);
    max = yakl::ParallelMax<real,memDevice>(data);
```
(or)
```c++
    sum = yakl::ParallelReduction<real,memDevice>(data).sum();
    min = yakl::ParallelReduction<real,memDevice>(data).min();
    max = yakl::ParallelReduction<real,memDevice>(data).max();
```

**Comment by mrnorman** [comment]
I'll give this some thought. The documentation recommends using yakl::intrinsics::minval sum, maxval, and product currently. Having the use pass the number of elements to the reduction class allows greater flexibility to use non-YAKL-Array data if they want. But I would be happy to accept a YAKL Array OR a std::is_integral parameter to allow this behavior. Does that sound like a good plan?

**Comment by mrnorman** [comment]
On second thought, the second option you gave is pretty similar to just using the recommended `yakl::intrinsics::maxval(data)`. I'll go through the docs and see if I use the Parallel* classes and replace it with the intrinsics function to make sure the user is properly encouraged to use the easier and safer approach.

**Comment by mrnorman** [comment]
I'm going to mark this as closed for now, but if I read the issue incorrectly or missed something, please feel free to reopen it.
