### ISSUE TITLE
[CUDA][HIP][SYCL] Get runtime meminfo

### ISSUE THREAD

**Issue by abagusetty** [mrnorman/YAKL#115]
CUDA: `cudaMemGetInfo`
HIP: `hipMemGetInfo`
SYCL:
```c++
    mtotal = myDev->get_info<sycl::info::device::global_mem_size>();
    mfree  = myDev->get_info<sycl::ext::intel::info::device::free_memory>();
```

**Comment by mrnorman** [comment]
Thanks for this. I'm not certain we converged on a strategy here: to update to 4-8GB default initial allocation or to base it on a proportion of the available memory on the device. I'll jump on this soon.
