### ISSUE TITLE
Vectorization and index_t

### ISSUE THREAD

**Issue by mwarusz** [mrnorman/YAKL#144]
I have been trying to use YAKL packs to vectorize a piece of code. I ran into issues due to the YAKL array index type.
YAKL uses `unsigned int` as the index type, which is prohibiting vectorization in some compilers. To show this, here
is a minimal example of adding two 2d arrays on Compiler Explorer, which is modeled on what I think YAKL packs
do under the hood.

https://godbolt.org/z/a1E6cMaM8

For this example neither GCC nor Clang generate vector instructions when `index_t` is set to `unsigned int`, despite
using `__restrict__` and simd pragmas. They both vectorize this code (although Clang does something wild) if `index_t` is pretty much anything else: `int`, `size_t`, or `unsigned short`. My original code using YAKL packs also vectorizes and speeds up when I change `index_t` to something else.  

Since I have seen benefits of using 32 bit indices on GPUs, I think that making `index_t` depend on the chosen backend
may be a good option.

**Comment by mrnorman** [comment]
That's really helpful to know. Hopefully I can work on this soon. Strange that unsigned ints would throw things off. Any other thing you think might be inhibiting vectorization?

**Comment by mwarusz** [comment]
Not to my knowledge. I found this old (and resolved) GCC bug that discusses problems with `unsigned int` and vectorization: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=48052. In that issue the problematic loops were much simpler though, so there still might be similar issues for more complex patterns.

**Comment by mrnorman** [comment]
Well, it's not just SIMD that's slowing down because of this :-/. It's the rest of the code too!

**Comment by mrnorman** [comment]
I've got a PR addressing this here: https://github.com/mrnorman/YAKL/pull/145
