### ISSUE TITLE
Could you provide some examples on how to run YAKL with multiple GPUs?

### ISSUE THREAD

**Issue by anyin233** [mrnorman/YAKL#152]

**Comment by mrnorman** [comment]
Hi, thanks for the github issue. YAKL is typically used on multiple GPUs with MPI. YAKL doesn't currently have a direct concept of viewing multiple GPUs per MPI task. As an example of using YAKL with multiple GPUs with MPI, please see:
https://github.com/mrnorman/miniWeather
Specifically: https://github.com/mrnorman/miniWeather/blob/main/cpp/miniWeather_mpi_parallelfor.cpp

**Comment by anyin233** [comment]
Thanks for your help.

**Comment by mrnorman** [comment]
NP. Feel free to reach out if anything else comes up. I should probably add a note on the higher-level documentation about examples of doing this.

**Comment by mrnorman** [comment]
OK, got the examples in the documenation wiki:

https://github.com/mrnorman/YAKL/wiki/Using-Multiple-GPUs-with-YAKL

And it's referenced from the front level wiki page now.
