### ISSUE TITLE
Segfault in ScalarLiveOut hostWrite on NVHPC

### ISSUE THREAD

**Issue by Goobley** [mrnorman/YAKL#165]
I'm using nvcc from the nvhpc 24.5-1 docker image, and a segfault is frequently (but not 100%) triggered inside `hostWrite` for `ScalarLiveOut`. This only occurs at higher host optimisation levels, with an almost guarantee at `-O3`. I am experiencing this in relation to the use of `minloc`. The last output with `YAKL_VERBOSE` is:

```
*** [YAKL_VERBOSE] Launching parallel_for labeled "Compute wphi" with 972800 threads (label: "Compute wphi")
*** [YAKL_VERBOSE] Allocating device reduction scalar of size 4 bytes
*** [YAKL_VERBOSE] Allocating device reduction temporary storage of size 5887 bytes
*** [YAKL_VERBOSE] Launching device reduction
*** [YAKL_VERBOSE] Initiating device to host memcpy of reduction scalar value of size 4 bytes
*** [YAKL_VERBOSE] Deallocating device reduction scalar
*** [YAKL_VERBOSE] Deallocating device reduction temporary storage
*** [YAKL_VERBOSE] Allocating device, C-style, rank 1 Array of size 4 bytes (label: "ScalarLiveOut_data")
*** [YAKL_VERBOSE] Launching parallel_for labeled "Unlabeled" with 1 threads (label: "Unlabeled")
Segmentation fault
```

I can follow the execution in cuda-dbg until the device launch of the kernel in `hostWrite` at which point a segfault pops up. But everything going into that kernel looks sane: the single entry array is properly allocated and has a reference count of 4 (not in danger of being deallocated), and the bounds are correct with `nIter == 1`.

Weirdly I have multiple `maxloc`s in the code that have never had an issue, but `minloc` has triggered this issue multiple times.
A temporary workaround for the sake of having reductions like `minloc` work more reliably is to update the constructor for `ScalarLiveOut` to:

```c++
    explicit ScalarLiveOut(T val, Stream stream = Stream() ) {
      Array<T, 1, memHost, styleC> host_data("ScalarLiveOut_data", 1);
      host_data(0) = val;
      data = host_data.createDeviceCopy(stream);
    }
 ```

For the sake of clarity, I have experienced this issue both with and without my adjustments to mutex handling in YAKL. I would like to understand what the origin of this issue is, but I am stuck for debugging it further.

**Comment by mrnorman** [comment]
I wonder if this is due to a bug I recently encountered in nvhpc where they don't correctly scope things in YAKL_SCOPE -- i.e., `auto &var = this->var;` or `auto &var = ::var` are not correctly brought into *local* scope, and therefore they are copied by reference into lambdas rather than by value. Regardless, I'm going to do two things.
1. Implement your proposed fix
2. Use YAKL_SCOPE throughout instead of `auto &var`. Since YAKL now does `auto &var = std::ref(this->var).get()` throughout, this should hopefully fix the issue.
