### ISSUE TITLE
Add custom stream capabilities

### ISSUE THREAD

**Issue by mrnorman** [mrnorman/YAKL#43]

**Comment by mrnorman** [comment]
@abagusetty , after some though, I think this will be harder than first assumed. The pool allocator works so efficiently because the allocations and deallocations are non-blocking. This also means pointers are technically being used after being deallocated and reassigned. This works only because GPU work is performed in order, so the deallocated pointer is no longer being used by the time the same pointer is used later as another variable.

If we start using streams, then the we'd either: (1) have to make allocations and deallocations blocking (which would likely significantly decrease the efficiency for our use cases), or (2) have to have data for those kernels pulled from a separate pool, which would require book-keeping from the user and rethought of how to expose the pool allocator.

What are your thoughts?

**Comment by mrnorman** [comment]
I think what I'll do here is implement it, but if the pool is turned on and the user pushes a stream, then I'll throw a warning to stdout that the pool can lead to pointer aliasing in concurrent kernels leading to wrong answers and that the user needs to be very careful that they know what they're doing.

**Comment by abagusetty** [comment]
@mrnorman Sorry for slow response, I was snowed under recently and had only partially sketched out the working on this task. I was putting down few points on the multi-stream/pool case and had few questions regarding the design and the scope of concurrent operations (both compute/data transfer) that YAKL could launch in general without a lot of book-keeping by a user. May be few sync points at stream level (cudaStreamSync). The question of whether to use events along with stream (binding/dependency) is still a design question. This approach would complicate the design but ensure correctness under the hood. 

Please let me know if you have some time (30 mins) next week for a quick chat to see how CUDA/HIP can work and its similarity and differences with SYCL

**Comment by mrnorman** [comment]
Thanks @abagusetty . @berrill  and I had a chat just now, and we have an idea (well...Mark had the idea, not me, haha) that's likely similar to your own.

We'll add logic to pool that will maintain a list of outstanding deallocations that are tied to "events" (whatever they're called for a given backend). At each subsequent allocate and free call to the pool, we'll check that list's events and actually deallocate the pointers whose events have completed. This way, we cannot allocate an existing pointer while it's being used in another kernel.

From the user's perspective, this will require them (for all data used in asynchronous invocations) to specify a std::vector of stream IDs to the array constructor or to the yakl::allocate() call, and those will have parameter defaults of a vector with one item that is the default stream or queue. It's up to the user to correctly specify the stream IDs to which a variable is tied. Then, when deallocate is called either explicitly or implicitly after falling out of scope, the pool deallocate will be tied to those stream / queue IDs.

To create a stream or queue ID in YAKL, we'll create an abstraction `int yakl::add_stream()`, which will create a stream or queue behind the scenes and pass an int ID to the user to use when specifying a stream to array creations or kernel launches. We'll probably also add an `int yakl::remove_stream(int id)` so they don't have to be permanent after creation.

Even still, I will almost certainly be printing a warning by default in stdout from the master task if the user has the pool enabled and adds a custom stream, just to let them know that YAKL's pool semantics can lead to unexpected behavior if they don't correctly specify streams when creating data.

Some issues:
* This will increase the memory usage compared the YAKL pool allocator's default behavior
* We need to rethink having a `zero` function in the pool allocator because if the user passes in a function that isn't a kernel, then we will have problems.

Any other potential issues come to mind at the moment?

**Comment by mrnorman** [comment]
Also have to consider the functor buffer for SYCL and for large CUDA functors. Might have to create a pool to hold them.

**Comment by mrnorman** [comment]
This has now been implemented with full functionality.
