### ISSUE TITLE
SYCL Problems

### ISSUE THREAD

**Issue by mrnorman** [mrnorman/YAKL#44]
- YAKL Intrinsics test fails with the `matinv_ge` routine for `FSArray` objects on JLSE iris with `-O2` or higher. Works with `-O1` or lower on JLSE and with all optimization levels on AMD, Nvidia, and CPU on all available machines.
  - `module load oneapi cmake`  (Jan 18, 2022)
- When `YAKL_DEBUG` is defined, SYCL segfaults on what appears to be the first kernel launch, but there's no trace beyond the kernel launch command itself.

**Comment by abagusetty** [comment]
@mrnorman Thanks, I was recently trying to catch up.

**Comment by mrnorman** [comment]
The intrinsics issue is likely a compiler issue. The YAKL_DEBUG might be my fault, but I'm finding it hard to debug with gdb-oneapi because it doesn't seem to delve into the kernel code itself.

**Comment by abagusetty** [comment]
Can you please give it a try on the ATS node since you already seem to have the problem setup. The debugging counters are far better there. I can help you with the a couple of env variables to hopefully help.

**Comment by mrnorman** [comment]
Sure thing, I'll try it out this afternoon. Thanks!

**Comment by mrnorman** [comment]
Behavior is the same for errors on arcticus, and I didn't seem to get any more debug information. I wonder if the reason I'm not getting debug info is that we're mem-copying the functor explicitly and the compiler doesn't actually know how the executable code relates to debug symbols.

**Comment by abagusetty** [comment]
Can you please share some reproduceable info (name of the unit test), myself and someone from Intel can take a dig at it

**Comment by mrnorman** [comment]
- Intrinsics bug (Works with `jlse_gpu_O1.sh` but not with `jlse_gpu_O3.sh`. Reproducer below:
  * `source jlse_gpu_O3.sh;  make -j Intrinsics;  ./Intrinsics/Intrinsics`
- `YAKL_DEBUG` segfault. Works without `-DYAKL_DEBUG` but fails with the flag. Reproducer below:
  * `source jlse_gpu_debug.sh;  make -j CArray;  ./CArray/CArray`

**Comment by abagusetty** [comment]
Thanks, I was able to reproduce the `YAKL_DEBUG` bug.

can you also post a diff for `jlse_gpu_01.sh` and `jlse_gpu_03.sh`, looks like these are your local files.

**Comment by mrnorman** [comment]
@abagusetty , please see the correction above regarding `YAKL_DEBUG`. It appears it fails with `-O0` but succeeds with `-O1`.

Sorry about forgetting to push those files to master. They're pushed now.

**Comment by abagusetty** [comment]
> 
Just an update, Intrinsic bug has been fixed in the nightly llvm compiler, Thanks to IntelCOE folks. Verified with -O{0..3} opt levels. The compilers at JLSE will be update very soon (few days) with the next SDK drop. 

I am yet to check the `YAKL_DEBUG` & `CArray`

**Comment by abagusetty** [comment]
@mrnorman PR #45 address the issues related to `YAKL_DEBUG`

**Comment by mrnorman** [comment]
YAKL_DEBUG now works, and Intrinsics bug was fixed in a compiler update.
