### ISSUE TITLE
printf for SYCL in yakl_throw

### ISSUE THREAD

**Issue by abagusetty** [mrnorman/YAKL#46]
Support for `sycl::printf` needs to be added to `yakl_throw` with appropriate function signature support. 
https://intel.github.io/llvm-docs/doxygen/namespacecl_1_1sycl_1_1ext_1_1oneapi_1_1experimental.html#a5116b4339ea3f3daa1aedec940cee03e

**Comment by mrnorman** [comment]
```C++
const CONSTANT char format[] = "KERNEL CHECK FAILED:\n   %s\n   %s\n";
sycl::ext::oneapi::experimental::printf(format,msg);
```

Is it possible to have a line that does:

```C++
char const *msg; // This is passed in
const CONSTANT char format[] = msg;
```

**Comment by mrnorman** [comment]
Fixed by the latest commit to master.
