### ISSUE TITLE
Citing YAKL

### ISSUE THREAD

**Issue by artv3** [mrnorman/YAKL#53]
Howdy! Is there preferred way to cite YAKL?

**Comment by mrnorman** [comment]
Thanks for reaching out. A pub specifically on YAKL is coming soon! For now, a footnote with the repo address or perhaps citing one of the following papers that *use* YAKL would work:

Norman, Matthew, and Jeffrey Larkin. "A holistic algorithmic approach to improving accuracy, robustness, and computational efficiency for atmospheric dynamics." SIAM Journal on Scientific Computing 42.5 (2020): B1302-B1327.

Lyngaas, Isaac, Matt Norman, and Youngsung Kim. "SAM++: Porting the E3SM-MMF cloud resolving model using a C++ portability library." The International Journal of High Performance Computing Applications (2021): 10943420211044495.

**Comment by sarats** [comment]
@mrnorman FYI, you can get a DOI for the repo from https://www.osti.gov/doecode/ which can be used in the pub as well.

**Comment by mrnorman** [comment]
@artv3 @sarats , YAKL can now be cited via this publication:

https://link.springer.com/article/10.1007/s10766-022-00739-0

Norman, M., Lyngaas, I., Bagusetty, A. et al. Portable C++ Code that can Look and Feel Like Fortran Code with Yet Another Kernel Launcher (YAKL). Int J Parallel Prog (2022). https://doi.org/10.1007/s10766-022-00739-0
