### ISSUE TITLE
Standalone run of SAMXX using p3/shoc using small number of ncrms with 8 gcds failed

### ISSUE THREAD

**Issue by xyuan** [mrnorman/YAKL#57]
I am testing the E3SM-MMF with new microphysics model P3/SHOC which are based on Kokkos backend on Crusher, and unable to use full GCDs of GPUs in one node, I can only run with maximum 4 gcds, when I run the case with 8 gcds, it crashed as below. But when I turn off MPI support in the code, I am able to run with up to 8 gcds. So it suggest to me that this is something related to MPICH GPU bind, could you help me to figure it out what is the reason? the script I used to build the code is as follows:
 
#!/bin/bash

source $MODULESHOME/init/bash
module purge
module load PrgEnv-cray/8.3.3 craype-accel-amd-gfx90a rocm/4.5.0
module load craype-network-ofi  cray-mpich/8.1.14
module load cray-hdf5 cray-netcdf cmake

unset ARCH
unset YAKL_ARCH
unset NCRMS
unset MACH
unset CC
unset CXX
unset FC

export MPIR_CVAR_GPU_EAGER_DEVICE_MEM=0
export MPICH_GPU_SUPPORT_ENABLED=1
export MPICH_SMP_SINGLE_COPY_MODE=CMA

export YAKL_DEBUG=true
export MACH="crusher"
export NCHOME=${NETCDF_DIR}
export NFHOME=${NETCDF_DIR}
export MPIHOME=${CRAY_MPICH_DIR}
export NCRMS=168
export CC=hipcc
export CXX=hipcc
export FC=ftn
export FFLAGS=" -O3 -h noomp -h noacc -I${ROCM_PATH}/include "
export CXXFLAGS="  -O3 -I${ROCM_PATH}/include "
export ARCH="HIP"
export YAKL_ARCH="HIP"
export YAKL_HIP_FLAGS="-O3 -D__HIP_ROCclr__ -D__HIP_ARCH_GFX90A__=1 --rocm-path=${ROCM_PATH} --offload-arch=gfx90a -x hip " 
export YAKL_HOME="`pwd`/../../../../../../../../externals/YAKL"
 
 
Crashed run information is:
 
:0: : Device-side assertion `' failed.
:0: : Device-side assertion `' failed.
:0:rocdevice.cpp            :2589: 500268655608 us: Device::callbackQueue aborting with error : HSA_STATUS_ERROR_EXCEPTION: An HSAIL operation resulted in a hardware exception. code: 0x1016
   Error! Temperature has <= 0 srun: error: crusher012: tasks 1-5,7: Aborted
srun: launch/slurm: _step_signal: Terminating StepId=102297.52
slurmstepd: error: *** STEP 102297.52 ON crusher012 CANCELLED AT 2022-04-22T13:31:34 ***
srun: error: crusher012: tasks 0,6: Terminated
srun: Force Terminated StepId=102297.52

**Comment by mrnorman** [comment]
Can you place this on E3SM's github page instead, since it may not be a YAKL issue?
