### ISSUE TITLE
Make any necessary corrections to SYCL streams

### ISSUE THREAD

**Issue by mrnorman** [mrnorman/YAKL#71]
SYCL streams have been implemented and tested, but it's possible there is a more efficient / standard way to achieve the streams functionality than what is currently implemented.

@abagusetty

**Comment by abagusetty** [comment]
Thanks @mrnorman I will get to this early next week. I've been bit snowed under SC deadlines approaching.

**Comment by mrnorman** [comment]
No rush! Thanks.
