### ISSUE TITLE
CUDA ffts can fail due to invalid alignment

### ISSUE THREAD

**Issue by mwarusz** [mrnorman/YAKL#72]
This code:
```
#include <YAKL.h>
#include <YAKL_fft.h>

using double1d = yakl::Array<double, 1, yakl::memDevice, yakl::styleC>;

int main()
{
  yakl::init();
  {
    double1d b("b", 1);
    int nx = 100;
    double1d a("a", nx+2);
    yakl::RealFFT1D<double> fft;
    fft.init(a, 0, nx);
    fft.forward_real(a);
  }
  yakl::finalize();
}
```
fails on `CUDA` with ```ERROR: YAKL CUFFT: /home/mwarusz/repos/yakl_playground/externals/YAKL/src/extensions/YAKL_fft.h: 217``` when using the default Gator settings. The documentation of [cufftExecD2Z](https://docs.nvidia.com/cuda/cufft/index.html#function-cufftexecr2c-cufftexecd2z) states that its input and output should be aligned to `cufftDoubleComplex` which is 16 bytes. However, the default Gator block bytes is `sizeof(size_t)`, which is insufficient to guarantee that.

Setting `GATOR_BLOCK_BYTES=16` is a workaround. Additionally, this message https://github.com/mrnorman/YAKL/blob/d52102d3be43ad8cc43c2f095817a5eb9a53f343/src/YAKL_InitConfig.h#L86
seems wrong. The default is clearly not `128*sizeof(size_t)`.

**Comment by mrnorman** [comment]
This is fixed by commit 75cd1c9. Your reproducer is in unit tests as well.

Seriously, thanks again, @mwarusz , for making this so easy for me to fix.
