### ISSUE TITLE
Wrap cuRand and other vendor PRNGs with YAKL_random.h

### ISSUE THREAD

**Issue by mrnorman** [mrnorman/YAKL#8]
Because the current PRNG is truly, truly awful.

**Comment by mrnorman** [comment]
I've added a new PRNG that's better, but it can still be improved. Gotta find a good PRNG with a very small internal state. CUDA still needs to route to curand

**Comment by sarats** [comment]
Curious about your opinion on 
SPRNG
http://sprng.org/

and DE Shaw's library:
https://www.deshawresearch.com/resources_random123.html

**Comment by mrnorman** [comment]
Thanks @sarats . I'll take a look later this week. In the meantime, do they have small internal states? That's the only requirement IMO for a GPU-friendly PRNG.

**Comment by mrnorman** [comment]
For simplicity, just using the 64-bit version of this: https://burtleburtle.net/bob/rand/smallprng.html

Improved testing.
