### ISSUE TITLE
Slicing with a range

### ISSUE THREAD

**Issue by mwarusz** [mrnorman/YAKL#80]
Could YAKL support continuous slicing with a range of indices, for example

```
Array<float,3,memDevice,styleC> c("c",nz,ny,nx);
auto d = c.slice<3>(Range(k, k + 2), COLON,COLON);
```
?

**Comment by mrnorman** [comment]
I've taken the past of least resistance for implementing this. The current solution is to use:
```C++
Array<float,3,memDevice,styleC> c("c",nz,ny,nx);
auto d = c.subset_slowest_dimension(k, k + 2);
```
This means slices with ranges on the slowest dimension now need `auto blah = arr.slice<N>(...).subset_slowest_dimension(l,u);`. It's a bit more text, but it can still be one-lined.
