### ISSUE TITLE
SYCL Improvements

### ISSUE THREAD

**Issue by mrnorman** [mrnorman/YAKL#83]
Go through the following commits in more detail before including:

e766e56c6aecb6869b46f338861b3f7f6808eb60
01bf8831cd5572fda080c7f594022e8b57c29b76
ebb38575777075e43d7c13ca1590ec53065a11d2

**Comment by abagusetty** [comment]
Should be mostly this commit: https://github.com/mrnorman/YAKL/commit/01bf8831cd5572fda080c7f594022e8b57c29b76
Taking a look at the HIP, CUDA stability

**Comment by abagusetty** [comment]
> Should be mostly this commit: [01bf883](https://github.com/mrnorman/YAKL/commit/01bf8831cd5572fda080c7f594022e8b57c29b76)
> Taking a look at the HIP, CUDA stability

Apologies. Turns out that CUDA, HIP, SYCL backends were fine.  Missed the CPU-side function signature. Fixed and will create a PR with other contents.
