### ISSUE TITLE
Fix unit test fortran compilation to avoid C++ link flags in Fortran linking

### ISSUE THREAD

**Issue by mrnorman** [mrnorman/YAKL#96]

**Comment by sarats** [comment]
Evidently, Cray ftn doesn't like the `-rdynamic` option. Removing that manually and adding ROCM library paths built the Fortran_Link program.

**Comment by sarats** [comment]
For `Fortran_Gator`

Removing `--rocm-path=/opt/rocm-5.1.0` and `-rdynamic` while adding `-L/opt/rocm-5.1.0/lib -lamdhip64` allowed Cray ftn to build .

**Comment by sarats** [comment]
Curious, what fixed it?

**Comment by mrnorman** [comment]
The introduction of `YAKL_UNIT_CXX_LINK_FLAGS` to the unit tests. We can link this to the C++-linked unit tests but not use it for Fortran-linked. Before, we used `CMAKE_EXE_LINKER_FLAGS`, which unilaterally added things to all unit tests and behaved poorly in Fortran linking on some machine / compilers.

**Comment by mrnorman** [comment]
https://github.com/mrnorman/YAKL/blob/main/unit/CArray/CMakeLists.txt#L10
